export { AboutBanner, } from './ui/AboutBanner/AboutBanner'
export { AboutClinic, } from './ui/AboutClinic/AboutClinic'
export { Doctors, } from './ui/Doctors/Doctors'
export { Services, } from './ui/Services/Services'
export { FAQ, } from './ui/FAQ/FAQ'
export { Feedback, } from './ui/Feedback/Feedback'

export { DoctorList, } from './ui/DoctorList/DoctorList'
export { ServiceList, } from './ui/ServiceList/ServiceList'
export { ContactsInfo, } from './ui/ContactsInfo/ContactsInfo'
export { DocumentList, } from './ui/DocumentList/DocumentList'
export { LegalInfo, } from './ui/LegalInfo/LegalInfo'
export { ControlOrganizationList, } from './ui/ControlOrganizationList/ControlOrganizationList'
export { InsuranceOrganizationList, } from './ui/InsuranceOrganizationList/InsuranceOrganizationList'
export { LinkList, } from './ui/LinkList/LinkList'